[manifest]
version = "1.0.0"
dump_lua = true
priority = 1000

# mod stuff

[[patches]]
[patches.module]
source = "nativefs.lua"
before = "main.lua"
name = "illusion_mod.nativefs"

[[patches]]
[patches.copy]
target = "main.lua"
position = "append"
sources = ["init.lua"]

# image edge fix

[[patches]]
[patches.pattern]
target = "game.lua"
position = "at"
match_indent = true
pattern = '''
self.ANIMATION_ATLAS[self.animation_atli[i].name].image = love.graphics.newImage(self.animation_atli[i].path, {mipmaps = true, dpiscale = self.SETTINGS.GRAPHICS.texture_scaling})
'''
payload = '''
self.ANIMATION_ATLAS[self.animation_atli[i].name].image = love.graphics.newImage(IllusionMod.image_data_or_path(self.animation_atli[i]), {mipmaps = true, dpiscale = self.SETTINGS.GRAPHICS.texture_scaling})
'''

[[patches]]
[patches.pattern]
target = "game.lua"
position = "at"
match_indent = true
pattern = '''
self.ASSET_ATLAS[self.asset_atli[i].name].image = love.graphics.newImage(self.asset_atli[i].path, {mipmaps = true, dpiscale = self.SETTINGS.GRAPHICS.texture_scaling})
'''
payload = '''
self.ASSET_ATLAS[self.asset_atli[i].name].image = love.graphics.newImage(IllusionMod.image_data_or_path(self.asset_atli[i]), {mipmaps = true, dpiscale = self.SETTINGS.GRAPHICS.texture_scaling})
'''

[[patches]]
[patches.pattern]
target = "game.lua"
position = "at"
match_indent = true
pattern = '''
self.ASSET_ATLAS[self.asset_images[i].name].image = love.graphics.newImage(self.asset_images[i].path, {mipmaps = true, dpiscale = 1})
'''
payload = '''
self.ASSET_ATLAS[self.asset_images[i].name].image = love.graphics.newImage(IllusionMod.image_data_or_path(self.asset_images[i]), {mipmaps = true, dpiscale = 1})
'''

# better anti-aliasing

[[patches]]
[patches.pattern]
target = "main.lua"
# this just introduces unnecessary blurring
pattern = '''
G.CANVAS:setFilter('linear', 'linear')
'''
position = "at"
payload = '''
G.CANVAS:setFilter('nearest', 'nearest')
'''
match_indent = true

# [[patches]]
# [patches.pattern]
# target = "game.lua"
# position = "at"
# match_indent = true
# pattern = '''
# self.SETTINGS.GRAPHICS.texture_scaling = self.SETTINGS.GRAPHICS.texture_scaling or 2
# '''
# # for my method of anti-alisasing, 1x textures are used
# payload = '''
# self.SETTINGS.GRAPHICS.texture_scaling = self.SETTINGS.GRAPHICS.texture_scaling or 1
# '''

[[patches]]
[patches.pattern]
target = "game.lua"
position = "after"
match_indent = true
pattern = '''
self.SHADERS[shader_name] = love.graphics.newShader("resources/shaders/"..filename)
'''
payload = '''
self.SHADERS[shader_name] = love.graphics.newShader(IllusionMod.shader_text_or_path({ path = "resources/shaders/"..filename, name = shader_name }))
'''